### ISSUE TITLE
Compile error makefile.unix:219: recipe for target 'craved' failed

### ISSUE THREAD

**Issue by 1000ml** [CooleRRSA/crave#11]
One error when compile on the latest Rasbian Stretch : 

`pi@rpi1:~/crave/src $ sudo make -f makefile.unix
/bin/sh ../share/genbuild.sh obj/build.h
g++ -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -Wunused-function -Wunused-variable -fpermissive -Wconversion-null -g -DBOOST_SPIRIT_THREADSAFE -I/home/pi/crave/src -I/home/pi/crave/src/obj -DUSE_UPNP=0 -DENABLE_WALLET -I/home/pi/crave/src/secp256k1/include -I/home/pi/crave/src/leveldb/include -I/home/pi/crave/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -o craved obj/alert.o obj/allocators.o obj/version.o obj/support/cleanse.o obj/checkpoints.o obj/netbase.o obj/addrman.o obj/base58.o obj/crypter.o obj/key.o obj/pubkey.o obj/ecwrapper.o obj/init.o obj/bitcoind.o obj/keystore.o obj/core.o obj/main.o obj/net.o obj/protocol.o obj/rpcclient.o obj/rpcprotocol.o obj/rpcserver.o obj/rpcmisc.o obj/rpcnet.o obj/rpcblockchain.o obj/rpcrawtransaction.o obj/rpcsmessage.o obj/script.o obj/scrypt.o obj/sync.o obj/txmempool.o obj/util.o obj/hash.o obj/noui.o obj/kernel.o obj/pbkdf2.o obj/chainparams.o obj/stealth.o obj/activemasternode.o obj/darksend.o obj/darksend-relay.o obj/instantx.o obj/masternodeconfig.o obj/masternodeman.o obj/masternode.o obj/masternode-payments.o obj/rpcdarksend.o obj/spork.o obj/crypto/hmac_sha256.o obj/crypto/hmac_sha512.o obj/crypto/ripemd160.o obj/crypto/sha1.o obj/crypto/sha256.o obj/crypto/sha512.o obj/smessage.o obj/db.o obj/miner.o obj/rpcdump.o obj/rpcmining.o obj/rpcwallet.o obj/wallet.o obj/walletdb.o obj/txdb-leveldb.o secp256k1/src/libsecp256k1_la-secp256k1.o -Wl,-z,relro -Wl,-z,now   -Wl,-Bdynamic -Wl,-Bdynamic -l boost_system -l boost_filesystem -l boost_program_options -l boost_thread -l db_cxx -l ssl -l gmp -l crypto -l miniupnpc -Wl,-Bdynamic -l z -l dl -l pthread /home/pi/crave/src/leveldb/libleveldb.a /home/pi/crave/src/leveldb/libmemenv.a
/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
makefile.unix:219: recipe for target 'craved' failed
make: *** [craved] Error 1`

Help :).

**Comment by CooleRRSA** [comment]
apt-get install gmp
