### ISSUE TITLE
needed libboost version for compiling

### ISSUE THREAD

**Issue by jagottsicher** [CooleRRSA/crave#14]
This issue is about the compatibility of newly compiled versions on linux 64bit machines against different libboost versions.

Let me explain:
I wanted to run crave 2.1.0.3 as a masternode on a ubuntu 16.04 but compiling failed because of too low memory (a VPS, 2GB, no swap possible because of btfrs).  So "bad luck", I sticked to the binary version 2.1.0 which runs smoothly so far after some little issues.

But later I thought to compile crave 2.1.0.3 on another machine and just copy it and maybe conribute it to the community, because nobody cares at the craveproject website so much for the linux versions. I compiled on ubutnu 14.04, but there the compiler comes out of the box with libboost version 1.54, but compiling worked fine and crave and also the masternode mode run smoothly.

So I copied craved in the corresponding directories on ubuntu 16.04 and tried to run it. Then the dark knight called  "Sir Sucks-a-lot" came by and shouted at me: 

`./craved: error while loading shared libraries: libboost_system.so.1.54.0: cannot open shared object file: No such file or directory
`

Obviously craved loads some shared libraries which must exist on the system in a specific version, but on ubuntu 16.04 I can not (and don want) downgrade. Also maybe other libs also needs to be downgraded later - not a sustainable way. But on 14.04 I also don't want to upgrade and recompile. The highest version I can reach is anyway 1.55, but ubuntu 16.04 comes around with 1.58 for libboost and if I want to contribute a complete Version for Linux 64bit as a binary later it needs to be statically compiled and not dynamically loading different libraries of specific versions.

**Is it possible to change that and to let people on 64bit linux machines upgrade to 2.1.0.3?**

If there is a simple solution afterwards I will contribute the 64bit and 32bit versions and keep them up-to-date.

**Comment by jagottsicher** [comment]
Feeling so lonely in this issue thread!

**Comment by CooleRRSA** [comment]
HI. If you use *nix systems you must know that static linking is completely removed from GNU. So it's impossible to do what you want.

**Comment by jagottsicher** [comment]
i don't want it statically linked but maybe the dependencies could be more generous?
is it not possible to let craved just use the version of libboost it find on the system it is started on?

**Comment by CooleRRSA** [comment]
It's not craved issue, it's *nix systems feature, so it's not possible.
