### ISSUE TITLE
error when using "make -f makefile.unix"

### ISSUE THREAD

**Issue by anmt91** [CooleRRSA/crave#15]
Could you pls help me?
I do step by step the document (https://github.com/starcoinproject/starcoin/blob/master/doc/build-unix.txt), but I don't know when I used "make -f makefile.unix", I had an issue.
I use linux 2017.3.
![screenshot from 2017-12-06 05-54-58](https://user-images.githubusercontent.com/26919951/33658545-17da2c32-da4b-11e7-80b1-7e2395225d6c.png)
Could I miss some libraries or miss any step?

**Comment by CooleRRSA** [comment]
Hi. Can you post there screenshot whrer you get first "error:" not "warning:"?

**Comment by anmt91** [comment]
Tks, I resolved it
